from enum import Enum


class SymbolFormatEnum(Enum):
    UPPER_UNDERSCORE = "UPPER_UNDERSCORE"
    LOWER_UNDERSCORE = "LOWER_UNDERSCORE"
    UPPER_HYPHEN = "UPPER_HYPHEN"
    LOWER_HYPHEN = "LOWER_HYPHEN"
    LOWER = "LOWER"
    UPPER = "UPPER"
