# Generated by Django 2.2.9 on 2019-12-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=255, unique=True)),
                ('order_id', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=128)),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=20, max_digits=40)),
                ('amount', models.DecimalField(decimal_places=20, max_digits=40)),
                ('value', models.DecimalField(decimal_places=20, max_digits=40)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(blank=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Symbol')),
            ],
            options={
                'unique_together': {('exchange', 'symbol', 'amount', 'price', 'trade_time')},
            },
        ),
    ]
