# Generated by Django 2.2.8 on 2019-12-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
