# Generated by Django 2.2.8 on 2019-12-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='trade_time',
            new_name='time',
        ),
    ]
