# Generated by Django 2.2.8 on 2019-12-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20191223_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
            preserve_default=False,
        ),
    ]
