# Generated by Django 2.2.9 on 2019-12-24 09:33

from django.db import migrations, models
import django.db.models.deletion
import enums.symbol


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=16383)),
                ('url', models.URLField(blank=True)),
                ('symbol_format', models.CharField(choices=[('UPPER_UNDERSCORE', enums.symbol.SymbolFormatEnum('UPPER_UNDERSCORE')), ('LOWER_UNDERSCORE', enums.symbol.SymbolFormatEnum('LOWER_UNDERSCORE')), ('UPPER_HYPHEN', enums.symbol.SymbolFormatEnum('UPPER_HYPHEN')), ('LOWER_HYPHEN', enums.symbol.SymbolFormatEnum('LOWER_HYPHEN')), ('LOWER', enums.symbol.SymbolFormatEnum('LOWER')), ('UPPER', enums.symbol.SymbolFormatEnum('UPPER'))], default='UPPER_UNDERSCORE', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_base', to='exchange.Currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_quote', to='exchange.Currency')),
            ],
            options={
                'unique_together': {('base', 'quote')},
            },
        ),
    ]
