# Generated by Django 2.2.8 on 2019-12-20 06:50

from django.db import migrations, models
import enums.symbol


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='symbol_format',
            field=models.CharField(choices=[('UPPER_UNDERSCORE', enums.symbol.SymbolFormatEnum('UPPER_UNDERSCORE')), ('LOWER_UNDERSCORE', enums.symbol.SymbolFormatEnum('LOWER_UNDERSCORE')), ('LOWER', enums.symbol.SymbolFormatEnum('LOWER'))], default='UPPER_UNDERSCORE', max_length=128),
        ),
    ]
