# Generated by Django 2.2.8 on 2019-12-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_tick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tick',
        ),
    ]
