# Generated by Django 2.2.8 on 2019-12-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_delete_tick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='symbol',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_base', to='exchange.Currency'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_quote', to='exchange.Currency'),
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('base', 'quote')},
        ),
    ]
