# Generated by Django 2.2.8 on 2019-12-23 05:40

from django.db import migrations, models
import enums.symbol


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20191220_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='symbol_format',
            field=models.CharField(choices=[('UPPER_UNDERSCORE', enums.symbol.SymbolFormatEnum('UPPER_UNDERSCORE')), ('LOWER_UNDERSCORE', enums.symbol.SymbolFormatEnum('LOWER_UNDERSCORE')), ('UPPER_HYPHEN', enums.symbol.SymbolFormatEnum('UPPER_HYPHEN')), ('LOWER_HYPHEN', enums.symbol.SymbolFormatEnum('LOWER_HYPHEN')), ('LOWER', enums.symbol.SymbolFormatEnum('LOWER')), ('UPPER', enums.symbol.SymbolFormatEnum('UPPER'))], default='UPPER_UNDERSCORE', max_length=128),
        ),
    ]
